database:
  host: {{ or .DATABASE_HOST "127.0.0.1" }}
  port: {{ or .DATABASE_PORT 5432 }}
  user: {{ or .DATABASE_USER "root" }}
  password: {{ or .DATABASE_PASSWORD "" }}
  database: {{ or .DATABASE_NAME "" }}
  pool: {{ or .DATABASE_POOL_SIZE 5 }}
  sslmode: {{ or .DATABASE_SSLMODE "disable" }}
local_address: {{ or .LOCAL_ADDRESS ":9001" }}
other_peers: [{{ or .OTHER_PEERS "" }}]
otlp_endpoint: {{ or .OTLP_ENDPOINT "" }}
mtls:
  cert: $CERT
  cert_private_key: $CERT_PRIVATE_KEY
  cert_server: {{ or .CERT_SERVER "" }}
