/*
 * DCSA OpenAPI specification for Electronic Bill of Lading
 *
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the [Information Model 2022.Q4](https://dcsa.org/wp-content/uploads/2022/12/DCSA_Information-Model-2022.Q4-final.pdf). **Please be aware that version 2022.Q4 of the Information Model includes Reefers - this API does not include Reefers.** This API does not define the business rules regarding what is allowed to update at what time. For this the [Interface Standard for the Bill of Lading 2.0](https://dcsa.org/wp-content/uploads/2022/12/12-23-2022_DCSA_Interface_Standard_Bill_of_Lading_v2.0.pdf) should be consulted.  All other documents related to the Electronic Bill of Lading publication can be found [here](https://dcsa.org/standards/ebill-of-lading/)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v2/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/ebl/v2#v200). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.
 *
 * API version: 2.0.0
 * Contact: info@dcsa.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bill_of_lading

// DcsaResponsibleAgencyCode : A DCSA provided code for [UN/CEFACT](https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred3055.htm) code list providers: - ISO (International Standards Organization) - UNECE (United Nations Economic Commission for Europe) - LLOYD (Lloyd's register of shipping) - BIC (Bureau International des Containeurs) - IMO (International Maritime Organization) - SCAC (Standard Carrier Alpha Code) - ITIGG (International Transport Implementation Guidelines Group) - ITU (International Telecommunication Union) - SMDG (Shipplanning Message Development Group) - EXIS (Exis Technologies Ltd.) - FMC (Federal Maritime Commission) - CBSA (Canada Border Services Agency) - DID (Decentralized Identifier) - LEI (Legal Entity Identifier) - EPI (EBL Platform Identifier) - ZZZ (Mutually defined)  More details can be found on [GitHub](https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/codelistresponsibleagencycodes.csv).
type DcsaResponsibleAgencyCode string

// List of DCSAResponsibleAgencyCode
const (
	ISO_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "ISO"
	UNECE_DcsaResponsibleAgencyCode DcsaResponsibleAgencyCode = "UNECE"
	LLOYD_DcsaResponsibleAgencyCode DcsaResponsibleAgencyCode = "LLOYD"
	BIC_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "BIC"
	IMO_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "IMO"
	SCAC_DcsaResponsibleAgencyCode  DcsaResponsibleAgencyCode = "SCAC"
	ITIGG_DcsaResponsibleAgencyCode DcsaResponsibleAgencyCode = "ITIGG"
	ITU_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "ITU"
	SMDG_DcsaResponsibleAgencyCode  DcsaResponsibleAgencyCode = "SMDG"
	EXIS_DcsaResponsibleAgencyCode  DcsaResponsibleAgencyCode = "EXIS"
	FMC_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "FMC"
	CBSA_DcsaResponsibleAgencyCode  DcsaResponsibleAgencyCode = "CBSA"
	DID_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "DID"
	LEI_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "LEI"
	EPI_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "EPI"
	ZZZ_DcsaResponsibleAgencyCode   DcsaResponsibleAgencyCode = "ZZZ"
)
