/*
 * DCSA OpenAPI specification for Electronic Bill of Lading
 *
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the [Information Model 2022.Q4](https://dcsa.org/wp-content/uploads/2022/12/DCSA_Information-Model-2022.Q4-final.pdf). **Please be aware that version 2022.Q4 of the Information Model includes Reefers - this API does not include Reefers.** This API does not define the business rules regarding what is allowed to update at what time. For this the [Interface Standard for the Bill of Lading 2.0](https://dcsa.org/wp-content/uploads/2022/12/12-23-2022_DCSA_Interface_Standard_Bill_of_Lading_v2.0.pdf) should be consulted.  All other documents related to the Electronic Bill of Lading publication can be found [here](https://dcsa.org/standards/ebill-of-lading/)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v2/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/ebl/v2#v200). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.
 *
 * API version: 2.0.0
 * Contact: info@dcsa.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bill_of_lading

// PartyFunction : Specifies the role of the party in the context of the given Shipping Instruction. - OS (Original shipper) - CN (Consignee) - COW (Invoice payer on behalf of the consignor (shipper)) - COX (Invoice payer on behalf of the consignee) - MS (Document/message issuer/sender) - N1 (First Notify Party) - N2 (Second Notify Party) - NI (Other Notify Party) - DDR (Consignor's freight forwarder) - DDS (Consignee's freight forwarder) - HE (Carrier booking office (transportation office)) - SCO (Service contract owner - Defined by DCSA) - BA (Booking Agency) - ENR (Envelope Receiver)
type PartyFunction string

// List of partyFunction
const (
	OS_PartyFunction  PartyFunction = "OS"  // Original Shipper
	CN_PartyFunction  PartyFunction = "CN"  // Consignee
	COW_PartyFunction PartyFunction = "COW" // Invoice payer on behalf of the consignor (shipper)
	COX_PartyFunction PartyFunction = "COX" // Invoice payer on behalf of the consignee
	MS_PartyFunction  PartyFunction = "MS"  // Document/message issuer/sender
	N1_PartyFunction  PartyFunction = "N1"  // First Notify Party
	N2_PartyFunction  PartyFunction = "N2"  // Second Notify Party
	NI_PartyFunction  PartyFunction = "NI"  // Other Notify Party
	DDR_PartyFunction PartyFunction = "DDR" // Consignor's freight forwarder
	DDS_PartyFunction PartyFunction = "DDS" // Consignee's freight forwarder
	HE_PartyFunction  PartyFunction = "HE"  // Carrier booking office (transportation office)
	SCO_PartyFunction PartyFunction = "SCO" // Service contract owner - Defined by DCSA
	BA_PartyFunction  PartyFunction = "BA"  // Booking Agency
	ENR_PartyFunction PartyFunction = "ENR" // Envelope Receiver
)
