// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/bu_server/business_unit/bu_jwt_factory.go

// Package mock_business_unit is a generated GoMock package.
package mock_business_unit

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	business_unit "github.com/openebl/openebl/pkg/bu_server/business_unit"
	model "github.com/openebl/openebl/pkg/bu_server/model"
)

// MockJWTFactory is a mock of JWTFactory interface.
type MockJWTFactory struct {
	ctrl     *gomock.Controller
	recorder *MockJWTFactoryMockRecorder
}

// MockJWTFactoryMockRecorder is the mock recorder for MockJWTFactory.
type MockJWTFactoryMockRecorder struct {
	mock *MockJWTFactory
}

// NewMockJWTFactory creates a new mock instance.
func NewMockJWTFactory(ctrl *gomock.Controller) *MockJWTFactory {
	mock := &MockJWTFactory{ctrl: ctrl}
	mock.recorder = &MockJWTFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTFactory) EXPECT() *MockJWTFactoryMockRecorder {
	return m.recorder
}

// NewJWEEncryptor mocks base method.
func (m *MockJWTFactory) NewJWEEncryptor(authentication model.BusinessUnitAuthentication) (business_unit.JWEEncryptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewJWEEncryptor", authentication)
	ret0, _ := ret[0].(business_unit.JWEEncryptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewJWEEncryptor indicates an expected call of NewJWEEncryptor.
func (mr *MockJWTFactoryMockRecorder) NewJWEEncryptor(authentication interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewJWEEncryptor", reflect.TypeOf((*MockJWTFactory)(nil).NewJWEEncryptor), authentication)
}

// NewJWSSigner mocks base method.
func (m *MockJWTFactory) NewJWSSigner(authentication model.BusinessUnitAuthentication) (business_unit.JWSSigner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewJWSSigner", authentication)
	ret0, _ := ret[0].(business_unit.JWSSigner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewJWSSigner indicates an expected call of NewJWSSigner.
func (mr *MockJWTFactoryMockRecorder) NewJWSSigner(authentication interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewJWSSigner", reflect.TypeOf((*MockJWTFactory)(nil).NewJWSSigner), authentication)
}
