// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/bu_server/business_unit/bu_jws_signer.go

// Package mock_business_unit is a generated GoMock package.
package mock_business_unit

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	business_unit "github.com/openebl/openebl/pkg/bu_server/business_unit"
	model "github.com/openebl/openebl/pkg/bu_server/model"
)

// MockJWSSignerFactory is a mock of JWSSignerFactory interface.
type MockJWSSignerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockJWSSignerFactoryMockRecorder
}

// MockJWSSignerFactoryMockRecorder is the mock recorder for MockJWSSignerFactory.
type MockJWSSignerFactoryMockRecorder struct {
	mock *MockJWSSignerFactory
}

// NewMockJWSSignerFactory creates a new mock instance.
func NewMockJWSSignerFactory(ctrl *gomock.Controller) *MockJWSSignerFactory {
	mock := &MockJWSSignerFactory{ctrl: ctrl}
	mock.recorder = &MockJWSSignerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWSSignerFactory) EXPECT() *MockJWSSignerFactoryMockRecorder {
	return m.recorder
}

// NewJWSSigner mocks base method.
func (m *MockJWSSignerFactory) NewJWSSigner(authentication model.BusinessUnitAuthentication) (business_unit.JWSSigner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewJWSSigner", authentication)
	ret0, _ := ret[0].(business_unit.JWSSigner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewJWSSigner indicates an expected call of NewJWSSigner.
func (mr *MockJWSSignerFactoryMockRecorder) NewJWSSigner(authentication interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewJWSSigner", reflect.TypeOf((*MockJWSSignerFactory)(nil).NewJWSSigner), authentication)
}
